### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by bamsarts** [cranklin/Instagram-Bot#14]
Traceback (most recent call last):
  File "webstagrambot.py", line 212, in <module>
    main()
  File "webstagrambot.py", line 208, in main
    login()
  File "webstagrambot.py", line 89, in login
    c.setopt(pycurl.URL, instagramlink[0])
IndexError: list index out of range

**Comment by duedares11** [comment]
Facing the same issues here. :/

**Comment by taylorreid** [comment]
same issues when launching.

**Comment by jsavalle** [comment]
same here

**Comment by daandotninja** [comment]
same here
