### ISSUE TITLE
This Bot Is No Longer Compatible with the latest version of Web.stagram.com

### ISSUE THREAD

**Issue by MattA9K** [cranklin/Instagram-Bot#9]
Upon authentication the program is now crashing right after major updates were done to web.stagram:

Traceback (most recent call last):
  File "runbot.py", line 107, in <module>
    login(username, password)
  File "/Users/mateuszandrzejczuk/Documents/CiniCraft_Likebot/likebot.py", line 50, in login
    c.perform()
pycurl.error: (3, '<url> malformed')

**Comment by borgf** [comment]
Same error unable to find a solution to that

Traceback (most recent call last):
  File "test.py", line 185, in <module>
  main()
  File "test.py", line 181, in main
    login()
  File "test.py", line 71, in login
    c.perform()
pycurl.error: (3, '<url> malformed')

**Comment by jberglinds** [comment]
Same error.
Webstagram has been down for some days and has also changed name to just 'Websta'. Hopefully someone can fix the authorization!

**Comment by Chizenbop** [comment]
Same error.  This code is broken and useless now.

**Comment by marclave** [comment]
New project now, https://github.com/marclave/InstaBot can use this

**Comment by InfiniteAlpha** [comment]
marclave, I'm getting the following error: 

Traceback (most recent call last):
  File "instalikewebsta.py", line 109, in <module>
    login(br, profile)
  File "instalikewebsta.py", line 16, in login
    br.form = list(br.forms())[0]  # Used because the form name was not named  
IndexError: list index out of range

I received authorization on websta.me and I'm logged in to instagram and my user id and password in the file are correct. The profile.yml file is formatted the same as your file. Any suggestions would be much appreciated.

**Comment by marclave** [comment]
Hi InifiniteAlpha, Instagrams login has changed so now i am trying to fix it. Instagram has done a very good job to stop bots : P but will try to fix it

**Comment by marclave** [comment]
Hi Everyone, I have found a workaround for the instagram bot in the latest commit: f4523880f93c04066bdb7a7bb5eca3f5ea06087f
I also updated the README with the latest commit 5854910d0c2e2e8ad89c82854ff452f6d8de14d6, please follow it to ensure everything works
I know its not the same as before, it might not be better I have not tested more than 10 likes but it works. I know Instagram has a rate limit of 5000 requests per day. Please let me know of any issues, for now this is deemed closed :)

**Comment by diegotfcastro** [comment]
Do you have a new version ? i Can pay for working version.

**Comment by Chizenbop** [comment]
Should still work.  Working on my end

**Comment by corriedotdev** [comment]
You managed to get this version working? Sorry but that seems impossible as the webstagram has been long updated since.

**Comment by marclave** [comment]
@corriejgreen I got my own instagram bot working

**Comment by corriedotdev** [comment]
@marclave I downloaded your one only to be hit with errors i assumed was because outdated software. http://imgur.com/Zyck1PH If you know the solution that doesnt involve already adding liking to the instagram account then thats great because ive already tried that. 

Edit: Solution is what i posted earlier but when you get your access token likes must be part of the scope in the same authorization request. The API really is vague here but thats the solution.

**Comment by marclave** [comment]
@corriejgreen I shall add that to the documentation

**Comment by corriedotdev** [comment]
@marclave https://instagram.com/oauth/authorize/?client_id=CLIENT_ID&redirect_uri=REDIRECT_URI&response_type=token&scope=likes There is a short url that will complete the request without having to use the api console :) All the best!
- Corrie
